### ISSUE TITLE
TagLib - opusfile.h missing

### ISSUE THREAD

**Issue by Vdue** [sbooth/AudioFrameworks#5]
Related to XCode 4.5 OSX 10.8.2

I downloaded your recent AudioFramework and the latest TagLib files.

When compiling taglib I receive an error opus file.h missing. Well that's right the whole opus directory is missing in the project. I manually added the missing folder. It compiles with over hundred warnings, but I get a taglib.framework.

When adding the tag lib.framework to a new project and compile: Crash -> dyld: Library not loaded: @rpath/taglib.framework/Versions/A/taglib
  Referenced from: ..../Developer/Xcode/DerivedData/TestTagLib-.../Build/Products/Debug/TestTagLib.app/Contents/MacOS/TestTagLib
  Reason: image not found 

BTW - if I take the ready rolled TagLib.framework, that thing does not work either, opened an issue on their webpage.

**Comment by sbooth** [comment]
https://github.com/sbooth/AudioXCFrameworks replaces this
